# Generated by Django 6.1 on 2026-09-11 08:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='completed', max_length=20)),
                ('skills', models.CharField(blank=True, help_text='Pisahkan dengan koma, mis. Django, React, PostgreSQL', max_length=255)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('demo_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
