# Generated by Django 6.1 on 2026-09-20 08:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_tutorial_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('languages', 'Languages'), ('programming', 'Programming Languages'), ('fullstack', 'Fullstack'), ('database', 'Database'), ('cybersecurity', 'Cybersecurity'), ('tools', 'Tools'), ('robotic', 'Robotic'), ('design', 'Beside the Keyboard')], default='tools', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('proficiency', models.PositiveSmallIntegerField(default=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', '-proficiency', 'name'],
            },
        ),
    ]
