# Generated by Django 6.1 on 2026-09-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_seed_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
    ]
